### ISSUE TITLE
can't install 0.3.2 on M2.2.6

### ISSUE THREAD

**Issue by fballiano** [doofinder/doofinder-magento2#114]
setup:upgrade or setup:di:compile give this error:

`Fatal error:  Interface 'Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchCriteriaResolverInterface' not found in /opt/atlassian/pipelines/agent/build/vendor/doofinder/doofinder-magento2/Model/ResourceModel/Fulltext/Collection/SearchCriteriaResolver.php on line 14
`

**Comment by fballiano** [comment]
SearchCriteriaResolver was introduced in M2.3, is this module not compatible with 2.2? I coulnd't find any documentation about that.

**Comment by carlosescri** [comment]
Hi @fballiano. Seems that Magento is constantly performing changes in the code and it's difficult to provide a generic solution for all versions. We've managed to release 0.4.0, which introduces a sub-module dependency that varies depending on the version of your Magento.

It's being validated in the Marketplace but you can install it via Composer. Any feedback will be appreciated. Please, contact our Support Team in case of trouble. The answer is much faster than here.
