### ISSUE TITLE
All products missing after setting Magento 2.3.5 Search to Doofinder

### ISSUE THREAD

**Issue by ecompleteClem** [doofinder/doofinder-magento2#125]
Hi,

When we enable Doofinder as the preferred search method in Stores -> Configuration -> Catalog -> Catalog.

All products do not display on site. 

We have performed a reindex after enabling this feature, as well as refreshing cache (Config + FPC).

**Comment by ecompleteClem** [comment]
I created this issue 15 days ago and no one has commented / given any details surrounding this?

Can I get an update please?

**Comment by carlosescri** [comment]
Hi @ecompleteClem. Thank you for reporting. To get the best support, please, drop an email to support@doofinder.com. They centralize all the tickets. Anyway, ensure you set indexing strategy for catalog to Update On Save after reindexing.
