### ISSUE TITLE
Fatal Error: Uncaught Error: Call to member function getResults() on null

### ISSUE THREAD

**Issue by ecompleteClem** [doofinder/doofinder-magento2#130]
Latest codebase 0.4.3
M2.3.5-p1

Fatal error: Uncaught Error: Call to a member function getResults() on null in vendor/doofinder/doofinder-magento2/Helper/Search.php:99 Stack trace: #0

**Comment by ecompleteClem** [comment]
We have put our API key and all of that into the extension, if we visit a category page / search for anything this appears.

**Comment by ecompleteClem** [comment]
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
. Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":209977344,"emalloc_start":193197072} [] []
[2020-09-01 12:47:44] main.CRITICAL: Server error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
 {"exception":"[object] (Doofinder\\Api\\Management\\Errors\\WrongResponse(code: 0): Server error: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor=\"white\">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by carlosescri** [comment]
Hi @ecompleteClem. That seems to be a problem in the API side, not in the code. In these cases is better to contact support to see if there's an error in the service. Thanks for reporting.

**Comment by ecompleteClem** [comment]
Hi Carlos,

I have contacted Doofinder support and they said it's a conflict between Mirasvit Layered Navigation and the Doofinder Extension using the same classes. Thus the one extension fights the other extension.

**Comment by carlosescri** [comment]
🤦

**Comment by carlosescri** [comment]
Thanks for the info.
