### ISSUE TITLE
Don't send banner display stats event to Doofinder search service

### ISSUE THREAD

**Issue by carlosescri** [doofinder/doofinder-magento2#131]
The event is automatically counted in the search service (it actually knows it's sending a banner id so it can count the event itself).

Click event must be sent as is now.

**Comment by carlosescri** [comment]
Related to https://github.com/doofinder/doofinder-magento/issues/128

**Comment by magently** [comment]
@carlosescri Changes for M2: https://github.com/magently/doofinder-magento2/tree/feature/banners-display
