### ISSUE TITLE
Investigate Magento without MSI

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-magento2#186]
A customer had asked:
we can't enable multisource inventory because it is not necessary and consumes a lot of resources.
Don't you have compatible version without msi? 

Investigate if it is possible to have a version of the magento module that does not use that package.

https://doofinder.freshdesk.com/a/tickets/66065

**Comment by sofia-doofinder** [comment]
@alvanieto, @Aitor-Corrales 
There are some functionalities like the availability of the product or the stock we need this module. The idea would be check if we can have a version that doesn't use that module and don't provide the information given by this module in the custom API?

**Comment by Aitor-Corrales** [comment]
That's it

**Comment by sofia-doofinder** [comment]
But it would be a module compeltely different, isn't it? I mean, would be another repository with another versions, etc. So two codes for maintenance.

**Comment by sofia-doofinder** [comment]
**Nota:** Durante las dos semanas que he estado en soporte de 24 tickets de magento2 5 no han podido instalar el plugin por este problema.

**Comment by sofia-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/186?planning-poker) with ZenHub @abraham-doofinder @ivan-doofinder @eduardogomez97 @pedromcp90 @Aitor-Corrales

**Comment by sofia-doofinder** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/186?planning-poker) with ZenHub @sofia-doofinder

**Comment by daniel-kratohvil** [comment]
Hey guys!

It looks like the issue is back with 7.1
It was working OK for me with 7.0 in a Magento 2.4.5 installation with no MSI, but after upgrading to 7.1 is broken again.

The problem seems to be in the **Model/ProductRepository.php** file, where dependencies for **InventorySales** and **InventorySalesApi** were added again.

**Comment by sofia-doofinder** [comment]
A new release that fix the isse has been published. V.0.8.0
