### ISSUE TITLE
[Magento] Refactoring the way we treat website, store and storeview

### ISSUE THREAD

**Issue by CristobalDolz** [doofinder/doofinder-magento2#187]
Currently we use the magento website as a doofinder store and the magento storeview as an SE, which can potentially lead to collisions between SEs that have the same installation.

To avoid this it is recommended to use magento stores conceptually as doofinder stores, so that different magento storeviews can have the same language and currency without colliding (by belonging to different doofinder layer installations).

Both the possible programmatic approaches for this and the consequences for customers working with the current structure should be studied.

**Comment by Aitor-Corrales** [comment]
This issue is blocked by the development of that other issue. In order to set the search criterias correctly, we needed to store the website id in the datasources before. But now, we need the store_id in order to set the new search criterias and it wouldn't make sense to store it in the datasources anymore, taking into account the proximity of this development. What do you think about it?

**Comment by albertodoofinder** [comment]
@CristobalDolz this should be reanalyzed

**Comment by Aitor-Corrales** [comment]
Lo escribo en cristiano. Se ha hecho la consulta a experto de esta tarea con @carlosescri y se han sacado las siguientes conclusiones con respecto a las acciones a realizar para el correcto desarrollo de esta tarea:

- Dentro del plugin de Magento, modificar la estructura del payload que se va a enviar a DoofAPI para que, en la creación de los datasources, guarde dentro de las opciones el Store_id que le corresponde.
- Dentro del plugin de Magento, hacer que la instalación se guarde a nivel de store y no de website, para evitar problemas con search engines de misma moneda y lenguaje.
- Modificar el payload enviado a dftasks para que envíe el store_id además del website_id (En caso de que lo haya). Esto se tiene que hacer así para dar compatibilidad tanto a versiones anteriores del plugin como a aquellas que se instalen (y que generen la estructura del store/search engines) a posteriori de esta versión.
- Modificar los criterios de búsqueda en doofeeds para que se tenga en cuenta el store_id, además del website_id.

Queda por documentar de forma más explicita las acciones a realizar en caso de que un cliente con una versión posterior tuviese los problemas relativos a los que pretende resolver esta issue, cuya solución pasaría por almacenar en cada una de las opciones del datasource correspondiente el id de la store_view a la que está representando en Magento.

**Comment by Aitor-Corrales** [comment]
Con la salida de la nueva versión de Magento 2.4.6, han habido determinados cambios e incompatibilidades que han afectado a nuestro plugin. Además de deprecar alguna clase que se estaba empleando, ahora no se soportan versiones de php inferiores a la 8.0.
