### ISSUE TITLE
Calculate availability using all providers

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-magento2#190]
There are some magento2 users that have multiple providers for a product.
Actually when we're providing the stock_items attributes we're using only the "default provider" to calculate is the product is in stock or out of stock. Would be interesing if we obtain this value taking all availables providers and not just de "default" because can occour that one product is available with another provider and we're showing the product as out of stock.

![image.png](https://images.zenhubusercontent.com/62cc492d54a8bf1416c82b4d/f7ae6607-4911-4b9f-8f67-a42bf8c059a9)

Example of customer with this problem:
https://doofinder.freshdesk.com/a/tickets/76885

**Comment by sofia-doofinder** [comment]
I've seen that in the new module we're using the class `\Magento\InventoryCatalogApi\Api\DefaultStockProviderInterface` that wasn't used in the magently plugin. Seems that this clase only take care about the default provider not all of them.

**Comment by Aitor-Corrales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/190?planning-poker) with Zenhub @Aitor-Corrales @abraham-doofinder @eduardogomez97 @ivan-doofinder @sofia-doofinder
