### ISSUE TITLE
Magento2 - Replace return_path callback with postMessage

### ISSUE THREAD

**Issue by alvanieto** [doofinder/doofinder-magento2#192]

**Comment by sofia-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/192?planning-poker) with Zenhub @Aitor-Corrales @ivan-doofinder @abraham-doofinder @eduardogomez97 @sofia-doofinder
