### ISSUE TITLE
[Magento2] Obtain the sectors from an endpoint exposed in doomanager

### ISSUE THREAD

**Issue by Aitor-Corrales** [doofinder/doofinder-magento2#198]
Currently, we are hardcoding the sectors with their values into the different plugins. What we now want is to be able to obtain all of those from a single endpoint from doomanager in order to unify the code.

**Comment by Aitor-Corrales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/198?planning-poker) with ZenHub @abraham-doofinder @alvanieto @eduardogomez97 @ivan-doofinder @pedromcp90 @Aitor-Corrales

**Comment by ivan-doofinder** [comment]
@Aitor-Corrales This issue is to create the endpoint or to adapt it to magento2?

**Comment by Aitor-Corrales** [comment]
Both

**Comment by Aitor-Corrales** [comment]
This issue is for adapting it to Magento. We'll have another one in doomanager scope in order to create this endpoint.

**Comment by abraham-doofinder** [comment]
In an expert consultation with @agutierrezrodriguez , it became clear that this implementation is not necessary.
