### ISSUE TITLE
[Magento2] Remove create integration button and unify with the rest of the wizard

### ISSUE THREAD

**Issue by Aitor-Corrales** [doofinder/doofinder-magento2#199]
For creating the integration, now we have a button in the wizard, but it does not make any sense since the client only has to click it, and it is not interesting to keep it there anymore. We should make this process as part of the last step of the wizard.

**Comment by Aitor-Corrales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/199?planning-poker) with ZenHub @Aitor-Corrales @abraham-doofinder @alvanieto @eduardogomez97 @ivan-doofinder @pedromcp90

**Comment by sofia-doofinder** [comment]
El botón que comenta Aitor ya se quitó:



![Image](https://github.com/doofinder/doofinder-magento2/assets/92720455/6e68d613-1411-49a6-99e9-49fba9beae19)
