### ISSUE TITLE
[Magento2] Add description to  index processing status table

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-magento2#215]
The "Index processing status" table is updated after the installation process (just first indexation).

![image](https://user-images.githubusercontent.com/92720455/188677723-c3d27154-6fdc-4cb2-9619-bd190a5b956f.png)

To avoid misunderstanding with the customers, the idea would be add some description to this page so the user knows that this information is related just with the first indexation. We've to write some text and validate it with product.

**Comment by pedromcp90** [comment]
Hi @CristobalDolz , could you give me some feedback about the text we should use here?
I think that it could be something like:
> Note that this information refers to the first indexation process only

I've attached a screenshot, so you can preview how it would look
![Selection_350.png](https://images.zenhubusercontent.com/62cd7219d361726b07a6c950/8f94a3e7-d551-47ef-9fd0-eb2bf6309516)

**Comment by pedromcp90** [comment]
Released in v0.8.4
