### ISSUE TITLE
Magento2 - Send full language code to create-store endpoint

### ISSUE THREAD

**Issue by ivan-doofinder** [doofinder/doofinder-magento2#218]
Currently only the ISO code of the language is sent in each Search Engine when the installation request is made to the create-store endpoint. The complete language code (language-region) must be sent. E.g.: es-ES, es-MX, en-EN, en-GB...

Check if the platform supports the use of region codes in the language. If it does not, we discard the task.

**Comment by ivan-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/218?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @alvanieto @eduardogomez97 @ivan-doofinder @pedromcp90 @sofia-doofinder

**Comment by Renzo84** [comment]
Hi guys,

Is there any news about it? Sorry I can't get into Zenhub.

Thanks,

**Comment by ivan-doofinder** [comment]
@Renzo84 This task has not been started yet. If it is urgent for you, we move it to give it priority

**Comment by albertodoofinder** [comment]
@Renzo84 a new version has been plublished by @pedromcp90 to address this
