### ISSUE TITLE
Magento 2 - Including/excluding taxes option for doofinder aplication

### ISSUE THREAD

**Issue by Aitor-Corrales** [doofinder/doofinder-magento2#221]
There is an option for selecting the way the client wants the product's price to be displayed named "including and excluding taxes". This option shows in the product's template both prices, but giving the main focus to the including taxes one.

When we ask for the final price while this option is selected, we get the price including taxes too, but there is a problem with that, related with the way some clients tend to use this option: Sometimes they change which of the prices is shown as the main price in the products page in the template, giving the sensation that the doofinder application is not working as expected anymore because the price shown in our application is the one with taxes (as it should).

In order to palliate this situation, we could add another option into our doofinder option's site, inside Magento, allowing the client to change the way they want the price to be shown (and indexed) inside doofinder:

 * Using Magento's default configuration
 * With taxes
 * Without taxes 

This way, if a client wants to change the template AND also wants to get the excluding taxes price to get indexed, instead of the including taxes one, they will be allowed.

**Comment by Aitor-Corrales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/221?planning-poker) with Zenhub @Aitor-Corrales @abraham-doofinder @alvanieto @eduardogomez97 @ivan-doofinder @pedromcp90 @sofia-doofinder

**Comment by ivan-doofinder** [comment]
Miramos a ver si es más sencillo de implementar la opción de indexar ambos precios y que el cliente por custom template elija que mostrar
