### ISSUE TITLE
View installed Magento plugin version

### ISSUE THREAD

**Issue by ivan-doofinder** [doofinder/doofinder-magento2#224]
**Objetivo**: Facilitar a soporte la gestión de tickets de Magento

Crear un endpoint en el plugin de Magento que nos diga la versión actual del plugin instalada.
Este endpoint podrá ser ampliable para mostrar más información que se requiera acerca del estado de la instalación.

**Comment by ivan-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Plugins-Stones-62c83f6d35d5c0001a3cb5bb/issues/doofinder/doofinder-magento2/224?planning-poker) with Zenhub @abraham-doofinder @Aitor-Corrales @alvanieto @eduardogomez97 @ivan-doofinder @pedromcp90 @sofia-doofinder

**Comment by alvanieto** [comment]
Sería usar una aproximación similar a la que se hace con la url de config en otras plataformas

**Comment by Aitor-Corrales** [comment]
Finalmente este endpoint va a exponer más información de la que se tenía prevista en una primera instancia. Con el fin de dar una información más detallada acerca del entorno del cliente, se va a exponer también la versión de la plataforma del cliente, así como la estructura de stores que tiene almacenada, con el lenguaje correspondiente para cada una de ellas.

**Comment by Aitor-Corrales** [comment]
Se ha valorado reestimar la tarea debido a que el alcance de la misma ha cambiado.
