### ISSUE TITLE
Magento2 - Bug when indexing special price

### ISSUE THREAD

**Issue by ivan-doofinder** [doofinder/doofinder-magento2#226]
Hay un problema en la indexación de precios cuando se tienen configurado un "special price".

Tenemos en **Magento** los campos:
- **price** (precio original)
- **special_price** (precio de oferta)  

En **Doofinder** se está indexando:
- price -> campo **special_price** de Magento + IVA
- sale_price -> campo **special_price** de Magento sin IVA

En ningún caso se indexa el campo **price** de Magento, por lo que no se puede mostrar el precio original tachado en la capa.

Tickets relacionados: 
https://doofinder.freshdesk.com/a/tickets/77768
https://doofinder.freshdesk.com/a/tickets/79362
https://doofinder.freshdesk.com/a/tickets/76091

**Comment by ivan-doofinder** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Unplugged-62c7342b32b594001e03d82a/issues/doofinder/doofinder-magento2/226?planning-poker) with Zenhub @ivan-doofinder @abraham-doofinder @Aitor-Corrales @eduardogomez97 @sofia-doofinder

**Comment by sofia-doofinder** [comment]
Hello @alexsomet, the new release that fix this bug has been already published! So would be great if you can ask the customers to update the plugin and check if now it is fixed.

Thank you!

**Comment by alexsomet** [comment]
Hello @sofia-doofinder , thank you guys! 

I have sent the release to corresponding customers. I will let you know as soon as I get news from them.

**Comment by alexsomet** [comment]
First positive feedback! 
https://doofinder.freshdesk.com/a/tickets/77768
