### ISSUE TITLE
[Magento] Calculate the special_price taking into account the custom price rules

### ISSUE THREAD

**Issue by pedromcp90** [doofinder/doofinder-magento2#232]
Currently, we are not taking into account the custom price rules defined in Magento to calculate the special_price.
We should check if any of these rules are applicable to each product and reflect it in the special_price.

We should also keep in mind that these rules vary depending on the date and can be programmed to apply in a specific date range, even updating the discount past a date. 
We have to find a solution so that the prices are updated every time the rule changes, perhaps by scheduling an index shortly after each date the rule changes

Related ticket: 
https://doofinder.freshdesk.com/a/tickets/80985

Documentation:
https://experienceleague.adobe.com/docs/commerce-admin/marketing/promotions/catalog-rules/price-rules-catalog.html?lang=en

**Comment by Aitor-Corrales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Unplugged-62c7342b32b594001e03d82a/issues/doofinder/doofinder-magento2/232?planning-poker) with Zenhub @Aitor-Corrales @eduardogomez97 @ivan-doofinder @pedromcp90 @sofia-doofinder
