### ISSUE TITLE
[Magento] Reestablecer opción de seleccionar tamaño de imagen

### ISSUE THREAD

**Issue by sofia-doofinder** [doofinder/doofinder-magento2#329]
Notion: https://www.notion.so/Magento-resize-images-1361222f883a4739ad0659e07eca5f9a

**Comment by sofia-doofinder** [comment]
@ogomezba un par de preguntas:
- Qué es lo que se va a poner en el selector: "Base, Small, Thumbnail, Swatch" o "470x470, 370x370, 100x100, 50x50" o qué exactamente?
- No entiendo en el último punto cuando dices que se va a indexar la marcada con el tag "small", que es que vamos a coger esa y la vamos a redimensionar? o por qué no cogemos directamente el tamaño que tienen marcado?

**Comment by ogomezba** [comment]
Solución técnica discutida con @eduardogomez97 . La solución consistirá en la adición de una nueva picklist en la configuración del plugin que permitirá seleccionar un tamaño. Dicha selección se guardará en la base de datos de Magento tal y como se hace para el resto de configuraciones. Dicha configuración se utilizará en el momento de la indexación para generar la imagen correctamente.

Puntos adicionales importantes:
- Las imágenes resizeadas se guardan en la cache de Magento, que puede ser vaciada. No obstante, aquellas imágenes que se resizearon usando una de las diferentes configuraciones listadas en algún [view.xml](https://developer.adobe.com/commerce/frontend-core/guide/themes/configure/), aunque se vacíen de la caché se regeneran cuando se intenta acceder de nuevo a su enlace.
- No obstante, si el cliente ha modificado su instalación de Magento manualmente y ha anulado dicho comportamiento, las imágenes no se regenerarían automáticamente
- La imagen que se usa como base para la redimensión es la marcada con el tag "small". En caso de que el cliente no tenga marcada ninguna imagen con dicho tag, actualmente se indexa una imagen placeholder. Dicho comportamiento se mantendrá tras el cambio

**Comment by ogomezba** [comment]
> @ogomezba un par de preguntas:
> 
> * Qué es lo que se va a poner en el selector: "Base, Small, Thumbnail, Swatch" o "470x470, 370x370, 100x100, 50x50" o qué exactamente?
> * No entiendo en el último punto cuando dices que se va a indexar la marcada con el tag "small", que es que vamos a coger esa y la vamos a redimensionar? o por qué no cogemos directamente el tamaño que tienen marcado?

@sofia-doofinder A mi parecer, creo que sería menos confuso poner los tamaños (470x470, etc.). @IgnacioPursalsZ qué valores deberías mostrar en la picklist?

Respecto a lo de "small", ahora mismo siempre indexamos la imagen marcada como "small" y en tamaño original. Discutiendo con @IgnacioPursalsZ, hemos acordado que tenía sentido seguir eligiendo esa imagen (para no cambiar la imagen que ya se está indexando) y redimensionarla al tamaño elegido por el usuario. A priori sería más confuso si, adicionalmente del tamaño, cambiamos también la imagen indexada.

**Comment by IgnacioPursalsZ** [comment]
Lo mejor para estos campos sería como están definidos en la tarjeta:
- Magento Base Image: 470 × 470 píxeles
- Magento Small Image: 370 x 370 píxeles
- Magento Thumbnail Image: 100 x 100 píxeles
- Magento Swatch Image: 50 x 50 píxeles

**Comment by ogomezba** [comment]
Tras investigar un poco más, el comportamiento actual no es de seleccionar siempre la imagen con el tag "small", sino elegir la **primera imagen de la list** que tenga, o bien el tag **small** o bien **thumbnail**. Tras comentarlo con Ignacio, se decide mantener este comportamiento aunque se incluya el resize.
