### ISSUE TITLE
Stores Configuration tabs display is broken ?

### ISSUE THREAD

**Issue by aurelienInternetrama** [doofinder/doofinder-magento2#36]
Hi,
After installing, I got Stores > Configuration tabs broken : 
- Does not display left tabs column
- Only display last left column item content
cf screenshot

Got others installed extensions but occured only after Doofinder install.
Installation was tested by FTP drop and composer.

Tried to find something wrong in system.xml but all seems to be OK.

Am I doing something wrong ?

Thank you

_Magento V2.2.4_

![screenshot-doofinder-feed](https://user-images.githubusercontent.com/10830211/41406492-d50be784-6fcc-11e8-83c5-da38b2a0844d.png)

**Comment by carlosescri** [comment]
Hi @aurelienInternetrama . What's the version of the module you're using? How did you installed it? Did you clean cache?

You could try to execute this in the CLI:

```
$ php bin/magento setup:upgrade
$ php bin/magento setup:di:compile
$ php bin/magento cache:flush
```

**Comment by aurelienInternetrama** [comment]
Hi @carlosescri and thank you for reply.
Version I'm using is 0.1.4-beta

Two tests were done for installation :

Cache was cleaned (several times)
And command lines were already executed.

**Comment by magently** [comment]
Hello @aurelienInternetrama 

Could you provide content of etc/module.xml file?

**Comment by aurelienInternetrama** [comment]
Hi @carlosescri,
Here it is :

`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
    <module name="Doofinder_Feed" setup_version="0.1.4" />
</config>`

Thanks

**Comment by magently** [comment]
@aurelienInternetrama 
Anything in logs? Is this your first installation of the module?

**Comment by aurelienInternetrama** [comment]
Hi @magently,
Nothing in logs anywhere server or Magento.
Yes it's the first time I install this module for Magento 2 (already installed Magento 1 extension, really great work :) ).

Thought missing tabs were just hidden due to bad CSS or something about display but they're just not there in HTML.

Tab id "doofinder_config" is not a reserved one, not overriding or rewriting anything, I don't really understand the issue. XML files format seem OK. Magento command line told Doofinder_Feed well installed.

Is it possible there's an issue about Model files used in Stores > Config tab forms that would create break but I think that if it was a PHP issue, we got logs somewhere.

Really disappointed
Thanks

**Comment by magently** [comment]
We had the same problem but it was occurred by `<sequence>` tag in module.xml. We have already fixed it. We are not able to reproduce it. But we will keep looking at it.
