### ISSUE TITLE
Separate search and indexing

### ISSUE THREAD

**Issue by carlosescri** [doofinder/doofinder-magento2#51]
Now, when you choose Doofinder as Magento's search engine, Magento uses Doofinder indexer.

There should be a way to use Doofinder for search, but using data from Doofinder that may be indexed from other source, like a custom API process or a custom data feed.

The only requirement is that the ID field of the indexed items matches the ID of the product in the database.

**Comment by mebbopakko** [comment]
Hi,

Any update on this issue?
We are having the problem that every category shows at most 100 products and it seems to be related to the Doofinder 100 search results limit.

Is there a way to bypass this? Some quickfix?
