### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by kamalkech** [doofinder/doofinder-magento2#57]
Magento CLI 2.3.0

"doofinder/doofinder-magento2": "0.1.11-beta"

i get : 

Declaration of Doofinder\Feed\Search\IndexerHandler::isAvailable() must be compatible with Magento\Framework\Indexer\SaveHandler\IndexerInterface::isAvailable($dimensions = Array) in /app/vendor/doofinder/doofinder-magento2/Search/IndexerHandler.php on line 13

**Comment by carlosescri** [comment]
Hi @kamalkech. This issue should be fixed by https://github.com/doofinder/doofinder-magento2/pull/54.

**Comment by kamalkech** [comment]
:( #54 that s mean not fixed yet !!!

**Comment by carlosescri** [comment]
We have a problem with tests ☹️🤦🏻‍♂️

**Comment by kamalkech** [comment]
hop fixe this quickly and good luck.

**Comment by carlosescri** [comment]
Hi @kamalkech. We finally released a new version of the module (0.1.12-beta).

Our internal integration tests continue failing in Magento 2.3 but seems that it is a compatibility issue with the version of the testing framework and the code of the tests (which works for all previous Magento versions).

Devs said that the module will work in M2.3 so we've 🤞 and sent the new code to Magento's Marketplace and it passed all their automated checks so we're confident it will work and it's a matter of time we find a way to have those tests fixed.

The module is waiting for manual QA validation in the Marketplace but it's available for install from Packagist via Composer:

https://packagist.org/packages/doofinder/doofinder-magento2

Sorry for the delay and thanks for your patience.
