### ISSUE TITLE
No images in search result

### ISSUE THREAD

**Issue by 911gt3rs** [doofinder/doofinder-magento2#60]
It's been several months that i have this bug, but i can not find solution. Images only appears for new products. Currently, i have last version (0.1.11).

![doofinder](https://user-images.githubusercontent.com/33813714/53113160-33d11e80-3541-11e9-82b4-9eb06c4ce1cd.png)

**Comment by carlosescri** [comment]
Hi @911gt3rs, in the [PDF Manual](https://github.com/doofinder/doofinder-magento2/blob/master/Manual.pdf), in the Troubleshooting section, there're a couple of points about wrong image URLs being indexed and possible solutions. I recommend you to take a look. Also, better if you drop us a line to support@doofinder.com, so we can track these kind of issues from a single place :wink:.

**Comment by 911gt3rs** [comment]
Hi, I found the solution by helping me with the PDF Manual.
You have to add 2 lines in backend Magento.
Configuration > Général > Web

![media](https://user-images.githubusercontent.com/33813714/53701661-ad012900-3dff-11e9-9bb6-39fad9aaff27.png)
Thanks for your help.
