### ISSUE TITLE
Update docs to encourage the user to properly configure media path

### ISSUE THREAD

**Issue by carlosescri** [doofinder/doofinder-magento2#63]
If it's left unconfigured, getting images in processes run via cron may produce wrong paths.

**Comment by VincentMarmiesse** [comment]
Hi @carlosescri,

Sorry to bump an old issue, but I just installed the module on a Magento 2 and we don't have any images in Doofinder. What should I configure?

Thanks!

**Comment by carlosescri** [comment]
Hi @VincentMarmiesse please contact Doofinder Support. Things changed a lot in the module and is probably better to start from there. I'm closing this issue because we are managing issues in a different platform now.
