### ISSUE TITLE
Improvment: No Image placeholder in feed when product image missing

### ISSUE THREAD

**Issue by TommyChausson** [doofinder/doofinder-magento2#96]
Hi,

We note that the placeholder image was not send on the feed when product has no Image. Due to the if here : https://github.com/doofinder/doofinder-magento2/blob/master/Helper/Product.php#L295

Is'nt it a good id to make a system config to allow feed using placeholder if the image field is empty ?

Regards,

**Comment by carlosescri** [comment]
Hi @TommyChausson. You're right. A bit late but I think we'll be able to put our hands on this soon.
