### ISSUE TITLE
After update Magento 2.3.3 : pagination, filtering, sorting on catalog page doesn't work

### ISSUE THREAD

**Issue by Thomas-gt3** [doofinder/doofinder-magento2#98]
The part circled in red is not displayed. When i disabled doofinder and enabled MySql Search this part comes back.

![1](https://user-images.githubusercontent.com/57117461/68607949-161e5d80-04b2-11ea-8f06-bff3886a24a9.png)

**Comment by carlosescri** [comment]
Hi @Thomas-gt3. A bit late but we had lots of trouble with Magento versions. We've released 0.4.0, which should work properly. In case you need support, please contact our Support Team, the will be pleased to help (me too but that's the official support channel).
